version: "3.9"
services:
  detection_service:
    build:
      context: ./detection_service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017

  notification_service:
    build:
      context: ./notification_service
    ports:
      - "8001:8000"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
